
import java.util.ArrayList;
import javax.swing.JTextField;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author rjlcx
 */
public class Pedido extends javax.swing.JFrame {

    /**
     * Creates new form Pedido
     */
    public Pedido() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jtnombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jtdireccion = new javax.swing.JTextField();
        jrgrande = new javax.swing.JRadioButton();
        jrmediano = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtapellido = new javax.swing.JTextField();
        jrpequeño = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jrhawaiana = new javax.swing.JRadioButton();
        jrcarnes = new javax.swing.JRadioButton();
        jramericana = new javax.swing.JRadioButton();
        jrdeluxe = new javax.swing.JRadioButton();
        jrvegano = new javax.swing.JRadioButton();
        jrespecial = new javax.swing.JRadioButton();
        jtcantidad = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        Aceptar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Resultado = new javax.swing.JTextArea();
        Aplicar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nombre");

        jtnombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtnombreActionPerformed(evt);
            }
        });

        jLabel2.setText("Direccion");

        jtdireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtdireccionActionPerformed(evt);
            }
        });

        buttonGroup1.add(jrgrande);
        jrgrande.setText("Grande");
        jrgrande.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrgrandeActionPerformed(evt);
            }
        });

        buttonGroup1.add(jrmediano);
        jrmediano.setText("Mediano");

        jLabel3.setText("Tamaño de Pizza");

        jLabel4.setText("Apellido");

        jtapellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtapellidoActionPerformed(evt);
            }
        });

        buttonGroup1.add(jrpequeño);
        jrpequeño.setText("Pequeño");

        jLabel5.setText("Pizzas disponibles");

        buttonGroup2.add(jrhawaiana);
        jrhawaiana.setText("Hawaiana");
        jrhawaiana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrhawaianaActionPerformed(evt);
            }
        });

        buttonGroup2.add(jrcarnes);
        jrcarnes.setText("3 carnes");
        jrcarnes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrcarnesActionPerformed(evt);
            }
        });

        buttonGroup2.add(jramericana);
        jramericana.setText("Americana");
        jramericana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jramericanaActionPerformed(evt);
            }
        });

        buttonGroup2.add(jrdeluxe);
        jrdeluxe.setText("Deluxe");
        jrdeluxe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrdeluxeActionPerformed(evt);
            }
        });

        buttonGroup2.add(jrvegano);
        jrvegano.setText("Vegana");
        jrvegano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrveganoActionPerformed(evt);
            }
        });

        buttonGroup2.add(jrespecial);
        jrespecial.setText("Pizza especial ");

        jtcantidad.setText("1");
        jtcantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtcantidadActionPerformed(evt);
            }
        });

        jLabel6.setText("Cantidad de pizzas");

        Aceptar.setText("Pagar");
        Aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AceptarActionPerformed(evt);
            }
        });

        Resultado.setColumns(20);
        Resultado.setRows(5);
        jScrollPane1.setViewportView(Resultado);

        Aplicar.setText("Aplicar");
        Aplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AplicarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jtcantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jrcarnes)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jramericana)))
                                .addGap(18, 18, 18)
                                .addComponent(jrdeluxe))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(95, 95, 95)
                                .addComponent(jrespecial))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtapellido, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jtdireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jrgrande)
                                .addGap(9, 9, 9)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jrmediano)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jrpequeño))
                                    .addComponent(jLabel3)))
                            .addComponent(jrhawaiana)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(jrvegano))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Aplicar)
                        .addGap(288, 288, 288)
                        .addComponent(Aceptar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(112, 112, 112))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jtapellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtdireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jrgrande)
                            .addComponent(jrmediano)
                            .addComponent(jrpequeño))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrhawaiana)
                    .addComponent(jrcarnes)
                    .addComponent(jramericana)
                    .addComponent(jrdeluxe))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrvegano)
                    .addComponent(jrespecial))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtcantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 98, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Aceptar)
                    .addComponent(Aplicar))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtnombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtnombreActionPerformed
        // TODO add your handling code here:
        Usuario us=new Usuario();
        us.nombre(jtnombre.getText());
    }//GEN-LAST:event_jtnombreActionPerformed

    private void jrgrandeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrgrandeActionPerformed
        // TODO add your handling code here:
        String L;
        L="Pizza Grande";
    }//GEN-LAST:event_jrgrandeActionPerformed

    private void jtapellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtapellidoActionPerformed
        // TODO add your handling code here:
        Usuario us=new Usuario();
        us.apellido(jtapellido.getText());
    }//GEN-LAST:event_jtapellidoActionPerformed

    private void jramericanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jramericanaActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jramericanaActionPerformed

    private void jrdeluxeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrdeluxeActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jrdeluxeActionPerformed

    private void jrveganoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrveganoActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jrveganoActionPerformed

    private void jrhawaianaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrhawaianaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrhawaianaActionPerformed

    private void jrcarnesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrcarnesActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jrcarnesActionPerformed

    private void AceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AceptarActionPerformed
        // TODO add your handling code here:
        Inicio i=new Inicio();
        i.show();
        dispose();
        
    }//GEN-LAST:event_AceptarActionPerformed

    private void jtcantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtcantidadActionPerformed
        // TODO add your handling code here:
        String cant=(jtcantidad.getText());
    }//GEN-LAST:event_jtcantidadActionPerformed

    private void AplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AplicarActionPerformed
        // TODO add your handling code here:
        String nom=jtnombre.getText();
        String ape=jtapellido.getText();
        String dir=jtdireccion.getText();
        String can=(jtcantidad.getText());
        String opcc1=" ";
        String opcc2=" ";
        String pe="Pedido";
        String sp="CANTIDAD: ";
        String tam="Tamaño: "; 
        String com="Componente";
        String nam=" ";
        if (jrgrande.isSelected()){
            opcc1 = "Pizza Grande";
        } else if (jrmediano.isSelected()){
            opcc1 = "Pizza Mediano";
        } else if (jrpequeño.isSelected()) {
            opcc1 = "Pizza Pequeña";
        } 
        if (jrhawaiana.isSelected()){
            Pizzapiña pi=new Pizzapiña();
            pi.masa();
            pi.ingredientes();
            pi.promocion();
            nam="Pizza Hawaiana";
            opcc2= pi.masa()+pi.ingredientes()+pi.promocion();
        } else if (jrcarnes.isSelected()){
            Pizza3Carnes Carn=new Pizza3Carnes();
            Carn.masa();
            Carn.ingredientes();
            Carn.promocion();
            nam="Pizza 3 carnes";
            opcc2= Carn.masa()+Carn.ingredientes()+Carn.promocion();
        } else if (jramericana.isSelected()) {
            PizzaAmericana Am=new PizzaAmericana();
            Am.masa();
            Am.ingredientes();
            Am.promocion();
            nam="Pizza Americana";
            opcc2= Am.masa()+Am.ingredientes()+Am.promocion();
        } else if (jrdeluxe.isSelected()){
            PizzaDeluxe Del=new PizzaDeluxe();
            Del.masa();
            Del.ingredientes();
            Del.promocion();
            nam="Pizza Deluxe";
            opcc2= Del.masa()+Del.ingredientes()+Del.promocion();
        } else if (jrvegano.isSelected()){
            PizzaVegana Veg=new PizzaVegana();
            Veg.masa();
            Veg.ingredientes();
            Veg.promocion();
            nam="Pizza Vegana";
            opcc2= Veg.masa()+Veg.ingredientes()+Veg.promocion();
        } else if (jrespecial.isSelected()){
            PizzaEspecial Es=new PizzaEspecial();
            Es.masa();
            Es.ingredientes();
            Es.promocion();
            nam="Pizza Especial";
            opcc2= Es.masa()+Es.ingredientes()+Es.promocion();
        } 
        ArrayList<String> list = new ArrayList<String>();
        list.add(nom);
        list.add("\n");
        list.add(ape);
        list.add("\n");
        list.add(dir);
        list.add("\n");
        list.add(pe);
        list.add("\n");
        list.add("\n");
        list.add(tam);
        list.add(opcc1);
        list.add("\n");
        list.add(nam);
        list.add("\n");
        list.add(com);
        list.add("\n");
        list.add(opcc2);
        list.add("\n");
        list.add(sp);
        list.add(can);
        list.add("\n");
        for(int i=0;i<list.size();i++){
            Resultado.append(list.get(i));
        }
        
    }//GEN-LAST:event_AplicarActionPerformed

    private void jtdireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtdireccionActionPerformed
        // TODO add your handling code here:
        Usuario us=new Usuario();
        us.direccion(jtdireccion.getText());
    }//GEN-LAST:event_jtdireccionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pedido().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Aceptar;
    private javax.swing.JButton Aplicar;
    private javax.swing.JTextArea Resultado;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton jramericana;
    private javax.swing.JRadioButton jrcarnes;
    private javax.swing.JRadioButton jrdeluxe;
    private javax.swing.JRadioButton jrespecial;
    private javax.swing.JRadioButton jrgrande;
    private javax.swing.JRadioButton jrhawaiana;
    private javax.swing.JRadioButton jrmediano;
    private javax.swing.JRadioButton jrpequeño;
    private javax.swing.JRadioButton jrvegano;
    private javax.swing.JTextField jtapellido;
    private javax.swing.JTextField jtcantidad;
    private javax.swing.JTextField jtdireccion;
    private javax.swing.JTextField jtnombre;
    // End of variables declaration//GEN-END:variables
}
